# Generated by Django 4.1.2 on 2022-11-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_Offer', '0003_rename_first_name_course_course_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Code', models.CharField(max_length=100)),
            ],
        ),
    ]
