# Generated by Django 4.1.3 on 2022-11-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_Offer', '0005_all_course_course_title_all_course_credits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_course',
            new_name='All',
        ),
    ]
